package zsc.zzc.entity;

import java.util.List;

public class Course {

	private String id;

    private String name;

    private String teacherId;

    private String professionId;

    private String tagId;

    private String icon;

    private Integer type;

    private String intro;

    private String fitPeople;
    
    private List<Section> listSections;
    
    private Profession profession;
    
    private Teacher teacher;

	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

	public Profession getProfession() {
		return profession;
	}

	public void setProfession(Profession profession) {
		this.profession = profession;
	}

	public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.id
     *
     * @param id the value for course.id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.teacher_id
     *
     * @return the value of course.teacher_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.teacher_id
     *
     * @param teacherId the value for course.teacher_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setTeacherId(String teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.profession_id
     *
     * @return the value of course.profession_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getProfessionId() {
        return professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.profession_id
     *
     * @param professionId the value for course.profession_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setProfessionId(String professionId) {
        this.professionId = professionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.tag_id
     *
     * @return the value of course.tag_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.tag_id
     *
     * @param tagId the value for course.tag_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setTagId(String tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.icon
     *
     * @return the value of course.icon
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.icon
     *
     * @param icon the value for course.icon
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.type
     *
     * @return the value of course.type
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.type
     *
     * @param type the value for course.type
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.intro
     *
     * @return the value of course.intro
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.intro
     *
     * @param intro the value for course.intro
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setIntro(String intro) {
        this.intro = intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.fit_people
     *
     * @return the value of course.fit_people
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getFitPeople() {
        return fitPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.fit_people
     *
     * @param fitPeople the value for course.fit_people
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setFitPeople(String fitPeople) {
        this.fitPeople = fitPeople;
    }

	public List<Section> getListSections() {
		return listSections;
	}

	public void setListSections(List<Section> listSections) {
		this.listSections = listSections;
	}
}