package zsc.zzc.entity;

public class Login {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.user_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.type
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.username
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.password
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.time
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.ip
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String ip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.user_id
     *
     * @return the value of login.user_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.user_id
     *
     * @param userId the value for login.user_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.type
     *
     * @return the value of login.type
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.type
     *
     * @param type the value for login.type
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.username
     *
     * @return the value of login.username
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.username
     *
     * @param username the value for login.username
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.password
     *
     * @return the value of login.password
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.password
     *
     * @param password the value for login.password
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.time
     *
     * @return the value of login.time
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.time
     *
     * @param time the value for login.time
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.ip
     *
     * @return the value of login.ip
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.ip
     *
     * @param ip the value for login.ip
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip;
    }
}