package zsc.zzc.entity;

public class Profession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.name
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profession.college_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String collegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.id
     *
     * @return the value of profession.id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.id
     *
     * @param id the value for profession.id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.name
     *
     * @return the value of profession.name
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.name
     *
     * @param name the value for profession.name
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profession.college_id
     *
     * @return the value of profession.college_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profession.college_id
     *
     * @param collegeId the value for profession.college_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setCollegeId(String collegeId) {
        this.collegeId = collegeId;
    }
}