package zsc.zzc.entity;

import java.util.Date;

public class Resource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.section_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String sectionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.type
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.fullname
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String fullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.file_extension
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private String fileExtension;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resource.created_time
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.section_id
     *
     * @return the value of resource.section_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getSectionId() {
        return sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.section_id
     *
     * @param sectionId the value for resource.section_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setSectionId(String sectionId) {
        this.sectionId = sectionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.type
     *
     * @return the value of resource.type
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.type
     *
     * @param type the value for resource.type
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.fullname
     *
     * @return the value of resource.fullname
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.fullname
     *
     * @param fullname the value for resource.fullname
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.file_extension
     *
     * @return the value of resource.file_extension
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getFileExtension() {
        return fileExtension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.file_extension
     *
     * @param fileExtension the value for resource.file_extension
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setFileExtension(String fileExtension) {
        this.fileExtension = fileExtension;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resource.created_time
     *
     * @return the value of resource.created_time
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resource.created_time
     *
     * @param createdTime the value for resource.created_time
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}