package zsc.zzc.entity;

public class Tag {

    private String id;

    private String name;

    private String categoryId;

    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.id
     *
     * @param id the value for tag.id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.name
     *
     * @return the value of tag.name
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.name
     *
     * @param name the value for tag.name
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.category_id
     *
     * @return the value of tag.category_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.category_id
     *
     * @param categoryId the value for tag.category_id
     *
     * @mbggenerated Tue Apr 24 10:24:00 CST 2018
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
}